# Generated by Django 3.2.20 on 2023-11-15 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_colourcode_customer_customeraddress_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.items')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='stock_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Orders.stockdetails'),
        ),
    ]
